# DATABASE CONFIG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-template?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: 123456
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# SERVER CONFIG
server:
  servlet:
    context-path: /api
  port: 8080

# Log
logging:
  pattern:
    console: %blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n
    file: %blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n


# Customize
application:
  jwt:
    secret: abc123
    expiration: 3333
