# DATABASE CONFIG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-template?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: 123456
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池的配置信息
    maxActive: 20
    initialSize: 5
    minIdle: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# SERVER CONFIG
server:
  servlet:
    context-path: /api
  port: 8080

# Log
#logging:
#  pattern:
#    console: %blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n
#    file: %blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n
