# DATABASE CONFIG
spring:
  datasource:
    url: jdbc:h2:file:~/db
    username: root
    password: root
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

# SERVER CONFIG
server:
  servlet:
    context-path: /api
  port: 8080

# Log
#logging:
#  pattern:
#    console: %blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n
#    file: %blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n


# Customize
application:
  jwt:
    secret: abc123
    expiration: 3333
